//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodyweight
    {
        public int Id { get; set; }
        public System.DateTime DateOfLift { get; set; }
        public double WeightKG { get; set; }
    }
}
