//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_log.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Squat
    {
        public int Id { get; set; }
        [Display(Name = "Date")]
        [Required]
        public System.DateTime DateOfLift { get; set; }
        [Display(Name = "Weight")]
        [Required]
        public double WeightKG { get; set; }
        public int Repetitions { get; set; }
    }
}
